spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    http:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1

    datasource:
        url: jdbc:mysql://120.76.101.180:3306/cns?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        url: jdbc:mysql://116.193.51.100:3306/cns?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: cns
        password: cnscns
        driver-class-name: com.mysql.jdbc.Driver

    mail:
        host: webmail.dbond.net
        port: 25
        username: crm@dingbang.net
        password: dbond1234##
        properties:
            starttls.enable: false
            starttls.required: false
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

    thymeleaf:
        cache:  false
        mode: HTML

    devtools:
        restart:
            exclude: static/**,public/**

server:
    contextPath: /

hibernate:
    show_sql: true

context:
    listener:
        classes: pers.roamer.boracay.application.StartedListener
